all:

upload:
	rsync -a --progress --rsh=ssh \
		welcome-to-foss-2009-announcement-english.xhtml \
		w2foss-2009-what-is-foss-ori-idan-poster.odt \
		welcome-to-foss-2009-demo-hebrew.xhtml \
		"$$HOMEPAGE_SSH_PATH/w2foss-temp/"
